package com.brands.dao;
// Generated Apr 15, 2020, 11:07:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CreditAdding generated by hbm2java
 */
@Entity
@Table(name="credit_adding"
    ,catalog="brands"
)
public class CreditAdding  implements java.io.Serializable {


     private String code;
     private Double value;

    public CreditAdding() {
    }

	
    public CreditAdding(String code) {
        this.code = code;
    }
    public CreditAdding(String code, Double value) {
       this.code = code;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=11)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="value", precision=22, scale=0)
    public Double getValue() {
        return this.value;
    }
    
    public void setValue(Double value) {
        this.value = value;
    }




}


