package com.brands.dao;
// Generated Apr 15, 2020, 11:07:19 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name="order_details"
    ,catalog="brands"
)
public class OrderDetails  implements java.io.Serializable {


     private int id;
     private Orders orders;
     private Products products;
     private double amount;
     private double price;
     private int quanity;

    public OrderDetails() {
    }

    public OrderDetails(int id, Orders orders, Products products, double amount, double price, int quanity) {
       this.id = id;
       this.orders = orders;
       this.products = products;
       this.amount = amount;
       this.price = price;
       this.quanity = quanity;
    }
    public OrderDetails(Orders orders, Products products, double amount, double price, int quanity) {
        this.orders = orders;
        this.products = products;
        this.amount = amount;
        this.price = price;
        this.quanity = quanity;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORDER_ID", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRODUCT_ID", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="Amount", nullable=false, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="Price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }

    
    @Column(name="Quanity", nullable=false)
    public int getQuanity() {
        return this.quanity;
    }
    
    public void setQuanity(int quanity) {
        this.quanity = quanity;
    }




}


