package com.brands.dao;
// Generated Apr 16, 2020, 12:01:12 AM by Hibernate Tools 4.3.1


import javax.persistence.*;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products"
        , catalog = "brands"
)
public class Products implements java.io.Serializable {


    private int productId;
    private Category category;
    private Date createDate;
    private byte[] image;
    private String name;
    private double price;
    private String description;
    private String imageName;
    private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);
    /*nehal*/
    private Integer quantity;

    @Column(name = "quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /*nehal*/
    public Products() {
    }


    public Products(Category category, Date createDate, String name, double price) {
//        this.productId = productId;
        this.category = category;
        this.createDate = createDate;
        this.name = name;
        this.price = price;
    }

    public Products(Category category, Date createDate, byte[] image, String name, double price, String description, Set<OrderDetails> orderDetailses) {
//       this.productId = productId;
        this.category = category;
        this.createDate = createDate;
        this.image = image;
        this.name = name;
        this.price = price;
        this.description = description;
        this.orderDetailses = orderDetailses;
    }

    @Id


    @Column(name = "product_id", unique = true, nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "Create_Date", nullable = false, length = 10)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }


    @Column(name = "Image")
    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }


    @Column(name = "Name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "Price", nullable = false, precision = 22, scale = 0)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }


    @Column(name = "description", length = 225)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "imageName", length = 225)
    public String getImageName() {
        return this.imageName;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    @Override
    public String toString() {
        return "Products{" +
                "productId=" + productId +
                ", category=" + category +
                ", createDate=" + createDate +
                ", image=" + Arrays.toString(image) +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", description='" + description + '\'' +
                ", imageName='" + imageName + '\'' +
                ", orderDetailses=" + orderDetailses +
                '}';
    }


    @OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }

    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }


}


