package com.brands.dao;
// Generated Apr 16, 2020, 12:01:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="brands"
        , uniqueConstraints = @UniqueConstraint(columnNames="email")
)
public class Users  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String status;
     private String password;
     private String userRole;
     private String address;
     private String phone;
     private String email;
     private Double creditLimit;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Users() {
    }



    public Users(int userId, String userName, String status, String password, String userRole) {
        this.userId = userId;
        this.userName = userName;
        this.status = status;
        this.password = password;
        this.userRole = userRole;
    }
    public Users(int userId, String userName, String status, String password, String userRole, String address, String phone, String email, Double creditLimit, Set<Orders> orderses) {
       this.userId = userId;
       this.userName = userName;
       this.status = status;
       this.password = password;
       this.userRole = userRole;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.creditLimit = creditLimit;
       this.orderses = orderses;
    }
   
     @Id 

    
    @Column(name="User_id", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="User_Name", nullable=false, length=20)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Password", nullable=false, length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="User_Role", nullable=false, length=10)
    public String getUserRole() {
        return this.userRole;
    }
    
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone", length=11)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email",  unique=true, nullable=false,length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="credit_limit", precision=22, scale=0)
    public Double getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(Double creditLimit) {
        this.creditLimit = creditLimit;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }


    @Override
    public String toString() {
        return "Users{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", status='" + status + '\'' +
                ", password='" + password + '\'' +
                ", userRole='" + userRole + '\'' +
                ", address='" + address + '\'' +
                ", phone='" + phone + '\'' +
                ", email='" + email + '\'' +
                ", creditLimit=" + creditLimit +
                ", orderses=" + orderses +
                '}';
    }
}


